### ISSUE TITLE
Pyarchey crashes on Opensuse 64bit

### ISSUE THREAD

**Issue by Mirppc** [walchko/pyarchey#14]
so i installed pyarchey on several opensuse computers (all 64bit)  from 13.2 to Leap.

Here is a paste of the install info.

[code]
$ sudo pip install pyarchey
Downloading/unpacking pyarchey
  Downloading pyarchey-0.6.8.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pyarchey/setup.py) egg_info for package pyarchey

```
warning: no previously-included files matching '.gitignore' found under directory '*'
warning: no previously-included files matching '.travis.yml' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
```

Requirement already satisfied (use --upgrade to upgrade): psutil in /usr/lib64/python3.4/site-packages (from pyarchey)
Installing collected packages: pyarchey
  Running setup.py install for pyarchey
      File "/usr/lib/python3.4/site-packages/pyarchey/pyarchey.py", line 447
        print json.dumps(self.json)
                 ^
    SyntaxError: invalid syntax

```
warning: no previously-included files matching '.gitignore' found under directory '*'
warning: no previously-included files matching '.travis.yml' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
Installing pyarchey script to /usr/bin
```

  Could not find .egg-info directory in install record for pyarchey
Successfully installed pyarchey
Cleaning up...
[/code]

Now here is the error i get when running the program.

[code]
$pyarchey
Traceback (most recent call last):
  File "/usr/bin/pyarchey", line 9, in <module>
    load_entry_point('pyarchey==0.6.8', 'console_scripts', 'pyarchey')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/**init**.py", line 2235, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/lib/python3.4/site-packages/pyarchey/pyarchey.py", line 447
    print json.dumps(self.json)
             ^
SyntaxError: invalid syntax
[/code]

Not sure what is going wrong or how to fix it.

**Comment by walchko** [comment]
So if you are using Python 3.x then my 2.7 print statements won't work:

``` python
print 'this works for python 2', 42
print('this works for python3', 42)
```

Since I don't use python 3 and the package is only designed to work on 2.7, that is why. I can fix some of those easy python 2 to 3 errors, but there could be others that are harder. 

I also don't understand why it is complaining about about my .gitignore, travis, and .DS_Store (apple file) like it is??? However, those shouldn't be fatal 

Thanks for the help!

**Comment by walchko** [comment]
ok, so I should have fixed the `print` issue and uploaded a new package version 0.7 that installs on python 2.7 nicely. Let me know if you have more issues.
