### ISSUE TITLE
list index out of range in gentoo

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [walchko/pyarchey#4]
Trying in gentoo, but i get

```
pyarchey                                               0s 
Traceback (most recent call last):
  File "/usr/bin/pyarchey", line 9, in <module>
    load_entry_point('pyarchey==0.6.1', 'console_scripts', 'pyarchey')()
  File "build/bdist.linux-i686/egg/pyarchey/pyarchey.py", line 569, in main
  File "build/bdist.linux-i686/egg/pyarchey/pyarchey.py", line 361, in append
IndexError: list index out of range
```

**Comment by ghost** [comment]
Not yet support Gentoo distribution.

**Comment by walchko** [comment]
Sorry, I have been really busy :)

I put a fix in and it  "should" identify an unsupported distro as "Linux" and draw a penguin now. If you could verify it, then I will push it to pypi when I have a chance!

if you want to submit a cool gentoo ascii logo I can incorporate it.

**Comment by Alessandro-Barbieri** [comment]
From https://github.com/mikeantonacci/archey/blob/master/archey

``` python
'Gentoo':'''{color[0]}
{color[0]} __q@@@@m {results[0]}
{color[0]} _q@@@@@@@@@@_ {results[1]}
{color[0]} _@@@@@@@@@@@@@@m {results[2]}
{color[0]} q@@@@@@@@@@@@@@@@@_ {results[3]}
{color[0]} _@@@@@@@@@@##@@@@@@@h {results[4]}
{color[0]} @@@@@@@@@@@ ##@@@@@@@@_ {results[5]}
{color[0]} 7##@@@@@@@___@@@@@@@@@@, {results[6]}
{color[0]} ####@@@@@@@@@@@@@@@@@@ {results[7]}
{color[0]} ####@@@@@@@@@@@@@@@@ {results[8]}
{color[0]} q@@@@@@@@@@@@@@@@#W {results[9]}
{color[0]} q@@@@@@@@@@@@@@@@@@/ {results[10]}
{color[0]} _@@@@@@@@@@@@@@@@#@@ {results[11]}
{color[0]} q@@@@@@@@@@@@@@@#@##^ {results[12]}
{color[0]} m#@@@@@@@@@@@@@@#@#W
{color[0]} _q@@@@@@@@@@@@@#@#*>
{color[0]} p@@@@@@@@@@@#@##%
{color[0]} _##@@@@@##@#@#g
{color[0]} _#@@@@@@#@@
{color[0]} _p@@@@q
\x1b[0m'''
```

**Comment by walchko** [comment]
cool ... thanks!

**Comment by Alessandro-Barbieri** [comment]
Works!
